trigger:
  branches:
    include:
      - phase2

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Run Solar Flare Batch Inference'
  inputs:
    azureSubscription: 'SC-UDST-CCIT-DSAI3202-2'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az extension add -n ml -y
      az ml job create \
        --file azure/inference_job.yml \
        --resource-group rg-60305750 \
        --workspace-name Amazon-Electronics-Lab-60305750 \
        --stream
